### ISSUE TITLE
amaranth-yosys doesn't build on MacOS

### ISSUE THREAD

**Issue by robtaylor** [nmigen/nmigen-yosys#6]
Numerous issues are hit when building on MacOS (tested on Montaray and Ventura):
1) Assumes GNU tools behaviour
2) downloads linux WASI SDK
3) forces wasmtime < 0.33 - M1/M2 require at least 0.40.1

**Comment by whitequark** [comment]
It's not supposed to build on macOS. However, the wasmtime dependency should be relaxed; I'll do this in a moment.

**Comment by whitequark** [comment]
Relaxed the version requirement in af2958d.

**Comment by whitequark** [comment]
@robtaylor has confirmed that https://pypi.org/project/amaranth-yosys/0.10.0.dev47/ works on macOS.
